# brench/tdce.toml

# Grab total dynamic instructions from brili's profile output.
extract = 'total_dyn_inst: (\d+)'

# Run every .bril benchmark (adjust the glob if your repo differs).
benchmarks = './test_suite/*.bril'

# Optional: kill runaway programs (seconds).
timeout = 5

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.tdce]
pipeline = [
  "bril2json",
  "python3 tdce.py",
  "brili -p {args}",
]
